### PR TITLE
Added Er diagram and schema

### PR DESCRIPTION
**Pull request by pankhuri813**
- EmployeeProfile: Stores information about each employee, like their name, email, and contact number.

- SkillSet: Keeps track of the skills each employee has. It's linked to the EmployeeProfile.

- Department: Contains data on different departments in the organization. Each department has one department head, and this head is an employee from the EmployeeProfile table.

- JobPosition: Describes various job titles and the salary range for those jobs. Each job position is tied to a specific department.

- TaskAssignment: Manages the tasks assigned to employees. Each task is linked to an employee from the EmployeeProfile table.

- PerformanceReview: Holds reviews of employees. Both the employee being reviewed and the one conducting the review are from the EmployeeProfile table.

- Simple Relationships: SkillSet to EmployeeProfile: Each skill belongs to one employee. An employee can have many skills.

- Department to EmployeeProfile: Each department has one head, who is an employee. But an employee might not be the head of any department or could be the head of just one.

- JobPosition to Department: Each job title belongs to one department. A department can have many job titles.

- TaskAssignment to EmployeeProfile: Each task is assigned to one employee. An employee can have many tasks.

- PerformanceReview to EmployeeProfile: Each review involves two employees: one is getting reviewed and the other is conducting the review. An employee can have multiple reviews and can also review multiple employees

Here's a video for quick understanding of [Schema](https://drive.google.com/file/d/1QNF4jo1BhXWMtaI1CiHm90JAneEpQEYB/view?usp=sharing) and [ER Diagram](https://drive.google.com/file/d/1Kzbk6fhql5QUfExr4hoqLntTJZ-Rr27o/view?usp=sharing)

### CODE REVIEW

**Comment by PRASANNAPATHI** [comment]
No Diagrams are added in PR. 
And your videos are not accessible, they are not public accessible.

**Comment by pankhuri813** [comment]
Hey, I uploaded the jpg format of both the diagrams. Can you check once again?

**Comment by PRASANNAPATHI** [comment]
ER Diagram is missing with relationship types notations (such as 1-to-N,...)
TaskAssignment should have the managerID foreign key from employee entity, who assigns the task to the Employee.
Department should not have DeptHead. Because the JobPosition should have that.  But Department can have total no. of employees.

**Comment by pankhuri813** [comment]
Hey, Done with changes. Could You check once?

**Comment by PRASANNAPATHI** [comment]
In Schema, 
EmployeeProfile table should have DepartmentId and not DepartmentName, and DepartmentId should be connected as foreign key,
Please update it

**Comment by pankhuri813** [comment]
Updated. Please review once more.

**Comment by PRASANNAPATHI** [comment]
Yes @pankhuri813, Its fine now.

Please go ahead and merge it.

**Pull request merged**
